src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 */
class Personne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="float")
     */
    private $Depense;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDepense(): ?float
    {
        return $this->Depense;
    }

    public function setDepense(float $Depense): self
    {
        $this->Depense = $Depense;

        return $this;
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Personne;
use Doctrine\DBAL\Types\TextType;
use phpDocumentor\Reflection\Types\Integer;
use phpDocumentor\Reflection\Types\String_;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('Depense')
            ->add("ok", SubmitType::class, ["label"=>"OK"])
        ;
    }



    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
        ]);
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\PersonneType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PersonneController extends AbstractController
{

    /**
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/', name: 'home')]
    public function index(EntityManagerInterface $manager ): Response
    {
       $personne = $manager ->getRepository(Personne::class)->findBy([],['id' => 'DESC']);

        return $this->render('personne/index.html.twig', [
            'personnes' => $personne,
        ]);
    }


    #[Route('personne/ajouter', name:'personne_ajouter')]
    public function ajouter(Request $request, ManagerRegistry $manager):Response
    {
        //créer uen catégorie vide
        $personne = new Personne();

        $form = $this->createForm(PersonneType::class, $personne);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //entity manager
            $em=$manager->getManager();

            //dis a l'entity manager que je veux enregister ma catégorie
            $em->persist($personne);//Trouver pourquoi il ne reconait pas ce persist mais reconnais celui du modifier



            //je déclenche la requête
            $em->flush();

            //je retourne à l'accueil
            return $this->redirectToRoute("home");
        }

        return $this->render('personne/ajouter.html.twig', [
            "formulaire"=>$form->createView()
        ]);
    }

    #[Route('personne/modifier/{id}', name:'personne_modifier')]
    public function personne_modifier($id, Request $request, ManagerRegistry $doctrine){
        $repo=$doctrine->getRepository(Personne::class);
        $personne=$repo->find($id);

        $form = $this->createForm(PersonneType::class, $personne);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){

            $em=$doctrine->getManager();


            $em->persist($personne);

            $em->flush();

            return $this->redirectToRoute("home");
        }

        return $this->render("personne/modifier.html.twig", [
            "formulaire"=>$form->createView()
        ]);
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Symfony!{% endblock %} -Yohane ENDOKE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

templates/personne/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Ajouter une personne</h1>
    {{ form(formulaire) }}
{% endblock %}

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil {% endblock %}

{% block body %}

<h1>Gestion des dépenses de la  soirée X</h1>

<table class="table">
    <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Dépense</th>
        <th></th>
    </tr>
    {% for p in personnes %}
        <tr>
            <td>{{ p.nom}}</td>
            <td>{{ p.prenom }}</td>
            <td>{{ p.depense }}</td>
            <td><a href="{{ path("personne_modifier",{"id":p.id}) }}" class="btn btn-sm btn-warning">Modifier</a></td>
        </tr>
    {% endfor %}
</table>


<a href="{{ path("personne_ajouter") }}" class="btn btn-success">
    Ajouter une personne
</a>
    <a href="{{ path("personne_ajouter") }}" class="btn btn-primary">
        Calculer le remboursement
    </a>

{% endblock %}

templates/personne/modifier.html.twig
{% extends 'base.html.twig.' %}

{% block title %}modifier une personne{% endblock %}

{% block body %}
    <h1>modifier une catégorie</h1>
    {{ form(formulaire) }}

{% endblock %}